name: Run server-side tests

on:
  push:
    paths:
      - 'server/**'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Setup Node environment
      uses: actions/setup-node@v2
      with:
        node-version: 16.2.0

    - run: npm install
      working-directory: ./server

    - name: Run type-check
      working-directory: ./server
      run: npm run type-check

    - name: Run tests
      working-directory: ./server
      run: npm run test
